---
title: "Final Project"
author: "Brenda Yang, Charlie Bonetti, Nour Kanaan"
date: "7/19/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(gdata)
library(tidyverse)
library(sf)
library(readxl)
```

### map of depression across regions
```{r data}
dstate = read.xls("data/state depression rates 2020.xls")
astate = read.xls("data/State anxiety trends 2020.xls")
dtrends2020 = read.xls("data/April 2020 depression trends.xls")
dtrends2018 = read.xls("data/April 2018 depression trends.xls")
atrends2020 = read.xls("data/April 2020 anxiety trends.xls")
atrends2018 = read.xls("data/April 2018 anxiety trends.xls")
deathrate = read.csv("data/restriction rankings.csv")
covidrate = read_excel("data/April COVID Cases by State.xlsx")
```

```{r graph}
library(usmap)
library(ggplot2)

plot_usmap(data = dstate, values = "depression", color = "red") + 
  scale_fill_continuous(name = "depression searches", label = scales::comma) + 
  theme(legend.position = "right")
```


